bash to sh

diff --git a/libexec/bundlizer-install b/libexec/bundlizer-install
--- a/libexec/bundlizer-install
+++ b/libexec/bundlizer-install
@@ -12,18 +12,32 @@ set -e
 # Install Bundler apps
 
     install() {
-      local user=`echo $1 | cut -d '/' -f1`
-      local app=`echo $1 | cut -d '/' -f2`
-      if [ -n $user -a -n $app ]; then
-        local url="git://github.com/$user/$app.git"
-        cd $BUNDLES
-        git clone $url
-        bundle_install_at $BUNDLES/$app
-        install_bundle_exec_wrappers $BUNDLES/$app
-      else
-        echo "Option Format error. See '`basename $0` help'"
-        exit 1
-      fi
+      check_bundles_dir_exists && {
+        local user=`echo $1 | cut -d '/' -f1`
+        local app=`echo $1 | cut -d '/' -f2`
+        if [ -n $user -a -n $app ]; then
+          local url="git://github.com/$user/$app.git"
+          cd $BUNDLES
+          git clone $url
+          bundle_install_at $BUNDLES/$app
+          install_bundle_exec_wrappers $BUNDLES/$app
+        else
+          echo "Option Format error. See '`basename $0` help'"
+          exit 1
+        fi
+      }
+    }
+
+
+    check_bundles_dir_exists() {
+      [ ! -d $BUNDLES ] && mkdir $BUNDLES
+      return 0
+    }
+
+
+    check_apps_dir_exists() {
+      [ ! -d $APPS ] && mkdir $APPS
+      return 0
     }
 
 
@@ -43,13 +57,15 @@ set -e
 # Install bundle exec warppers to bundlizer exec bin
 
     install_bundle_exec_wrappers() {
-      local gem_path=$1
-      for bin in `get_gem_bin_files $gem_path`; do
-        bin_path=$APPS/$bin
-        create_bundle_exec_wrapper $gem_path $bin > $bin_path
-        chmod +x $bin_path
-        echo "It was installed \`$bin\` into $bin_path"
-      done
+      check_apps_dir_exists && {
+        local gem_path=$1
+        for bin in `get_gem_bin_files $gem_path`; do
+          bin_path=$APPS/$bin
+          create_bundle_exec_wrapper $gem_path $bin > $bin_path
+          chmod +x $bin_path
+          echo "It was installed \`$bin\` into $bin_path"
+        done
+      }
     }
 
 
